driving_distance_calculator.settings:
  type: config_object
  label: 'Driving Distance Calculator settings'
  mapping:
    google_api_key:
      type: string
      label: 'Google API key'
    pricing_mode:
      type: string
      label: 'Pricing mode'
    base_price:
      type: float
      label: 'Base price'
    rate_per_km:
      type: float
      label: 'Rate per km'
    rate_per_min:
      type: float
      label: 'Rate per minute'
    rate_per_kg:
      type: float
      label: 'Rate per kg'
    fragile_surcharge:
      type: float
      label: 'Fragile surcharge'
    tiers:
      type: sequence
      label: 'Pricing tiers'
      sequence:
        type: mapping
        mapping:
          max:
            type: float
            label: 'Maximum distance (km)'
          price:
            type: float
            label: 'Price per km'
    allow_client_fallback:
      type: boolean
      label: 'Allow client fallback'
    distance_lookup_retries:
      type: integer
      label: 'Distance lookup retries'
    cache_ttl_minutes:
      type: integer
      label: 'Cache TTL (minutes)'
